config/routes.rb
Clochette::Application.routes.draw do
  root 'home#index'

  resources :user_sessions, only: [:create]
  get 'login' => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout

  resources :users, except: [:show]

  resources :projects, only: [:index, :new, :create, :destroy] do
    resources :triggers, only: [:index, :create, :destroy]
  end

  post 'hooks/:project_id/:service_name' => 'payloads#create', as: :hook
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :triggers, dependent: :destroy

  validates_presence_of :name

  before_create :generate_uid

  def to_param
    uid
  end

  private

  def generate_uid
    self.uid = SecureRandom.hex(16)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_project, only: [:destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_path, notice: t('.success')
    else
      flash.now[:alert] = t('.invalid')
      render action: 'new'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: t('.success')
  end

  private

  def load_project
    @project = Project.find_by_uid!(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/views/projects/_form.html.haml
= form_for @project do |form|
  .form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'

  .actions
    = form.submit t('helpers.links.save'), class: 'btn btn-primary'
    = link_to t('helpers.links.back'), projects_path, class: 'btn btn-default'

app/views/projects/index.html.haml
%ol.breadcrumb
  %li.active
    = link_to t('layouts.application.projects')

%table.table
  %thead
    %tr
      %th
        = Project.human_attribute_name(:name)
      %th
        = t('.hook_url')
      %th
  %tbody
    - @projects.each do |project|
      %tr
        %td
          = project.name
        %td
          = hook_url project_id: project.uid, service_name: ':service_name'
        %td
          = link_to t('.triggers'), project_triggers_path(project), class: 'btn btn-primary'
          = form_for(project, method: :delete, html: {class: 'form-inline', style: 'display: inline;'}) do |form|
            = form.submit t('helpers.links.destroy'), data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-danger'

%p
  = link_to t('.new'), new_project_path, id: 'new_project'