config/routes.rb
Clochette::Application.routes.draw do
  root 'home#index'

  resources :user_sessions, only: [:create]
  get 'login' => 'user_sessions#new', as: :login
  delete 'logout' => 'user_sessions#destroy', as: :logout

  resources :users, except: [:show]

  resources :projects, only: [:index, :new, :create, :destroy] do
    resources :triggers, only: [:index, :create, :destroy]
  end

  post 'hooks/:project_id/:service_name' => 'payloads#create', as: :hook
end

app/views/layouts/_flash.html.haml
- if flash.any?
  #flash
    - {alert: 'alert alert-danger', notice: 'alert alert-info'}.each do |flash_key, css_classes|
      - if flash[flash_key]
        %div{class: css_classes}
          = flash[flash_key]

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %meta{charset: "utf-8"}
    %title
      = t('.title')
    %meta{content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=yes", name: "viewport"}
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all"
  %body
    - if current_user
      %header.navbar.navbar-default{role: 'navigation'}
        .navbar-header
          = link_to t('.title'), root_path, class: 'navbar-brand'
        %nav
          %ul.nav.navbar-nav
            %li
              = link_to projects_path do
                %i.glyphicon.glyphicon-list
                = t('.projects')
            %li
              = link_to users_path do
                %i.glyphicon.glyphicon-user
                = t('.users')
          %ul.nav.navbar-nav.navbar-right
            %li.navbar-text
              = current_user.email
            %li
              = form_tag(logout_path, method: :delete, class: 'navbar-form') do
                = submit_tag t('.logout'), class: 'btn btn-danger', id: 'logout'
    .container
      = render 'layouts/flash'
      .row
        .col-md-12
          = yield
    = javascript_include_tag 'application'